### ISSUE TITLE
Add Joystick TS and TR

### ISSUE THREAD

**Issue by GeorgeR1989** [GeorgeRobu/DemoLPCExpresso2016#2]
Add folder test to the root.
test\
.........joystick\
...........................\test_res (test resources)
...........................\test_spec (test specification)
...........................\test_rep (test report)

**Comment by RosianRad** [comment]
Added test_res and test_spec.
Awaiting review.

**Comment by RosianRad** [comment]
Reviewed test_spec.
No findings found.
Added test_rep.
Issue closed.
