### ISSUE TITLE
Add first version of Buzzer module in GIT

### ISSUE THREAD

**Issue by GeorgeR1989** [GeorgeRobu/DemoLPCExpresso2016#3]
Push first version of buzzer into git
Review the first version of the code after the push is finalized

**Comment by IoanBobar** [comment]
Added a draft still working on it

**Comment by IoanBobar** [comment]
Added a draft. Still working on it

**Comment by GeorgeR1989** [comment]
Module is in GIT. Some adaptations need to be done prior to integration. Issue closed
